PU2CLR AKC695X Arduino Library: Basic Methods
Basic Methods
Functions
void AKC695X::reset ()
Resets the system.
void AKC695X::setI2CBusAddress (int deviceAddress)
Sets the I2C bus device address.
void AKC695X::setup (int reset_pin)
Receiver startup.
void AKC695X::powerOn (uint8_t fm_en, uint8_t tune, uint8_t mute, uint8_t seek, uint8_t seekup)
Power the device on.
void AKC695X::setRegister (uint8_t reg, uint8_t parameter)
Sets a given register with a given value.
uint8_t AKC695X::getRegister (uint8_t reg)
Gets a given register content.
Detailed Description
SI47XX Arduino Library implementation
This Library is under construction......
This is an Arduino library for the AKC695X, BROADCAST RECEIVER, IC family.
It works with I2C protocol and can provide an easier interface for controlling the AKC695X devices.
This library was built based on AKC6955 stereo FM / TV / MW / SW / LW digital tuning radio document from "AKC technology". It also intend to be used on all members of the AKC695X family respecting, of course, the features available for each IC version.
This library can be freely distributed using the MIT Free Software model. Copyright (c) 2019 Ricardo Lima Caratti.
Contact: pu2cl.nosp@m.r@gm.nosp@m.ail.c.nosp@m.om
Basic
Function Documentation
getRegister()
uint8_t AKC695X::getRegister (uint8_t reg)
Gets a given register content.
It is a basic function to get a value from a given AKC695X device register
Parameters
reg register number to be read (0 ~ 26)
Returns
the register content
References AKC695X::deviceAddress.
Referenced by AKC695X::getAmCarrierNoiseRatio(), AKC695X::getAmCurrentSpace(), AKC695X::getCurrentChannel(), AKC695X::getFmCarrierNoiseRatio(), AKC695X::getRSSI(), AKC695X::getSupplyVoltage(), AKC695X::isCurrentModeFM(), AKC695X::isFmStereo(), AKC695X::isTuned(), AKC695X::isTuningComplete(), AKC695X::setFrequency(), AKC695X::setVolume(), and AKC695X::setVolumeControl().
powerOn()
void AKC695X::powerOn (uint8_t fm_en, uint8_t tune, uint8_t mute, uint8_t seek, uint8_t seekup)
Power the device on.
Starts the AKC695X with some parameters.
Parameters
fm_en 1 = FM mode; 0 = AM mode
tune If 1 Trigger tune process. The STC bit is set high when the tune operation completes
mute If 1 mute L/R audio
seek If 1 Trigger tune process. The STC bit is set high when the tune operation completes
seekup Seek direction control bit. 0 = Seek down; 1 = Seek up
References AKC695X::currentMode, akc595x_reg0::raw, akc595x_reg0::refined, REG00, and AKC695X::setRegister().
reset()
void AKC695X::reset ()
Resets the system.
References AKC695X::resetPin.
Referenced by AKC695X::setup().
setI2CBusAddress()
void AKC695X::setI2CBusAddress (int deviceAddress)
Sets the I2C bus device address.
You do not need use this function if your i2c device address is 0x10 (default value)
Parameters
deviceAddress
References AKC695X::deviceAddress.
setRegister()
void AKC695X::setRegister (uint8_t reg, uint8_t parameter)
Sets a given register with a given value.
It is a basic function to deal with the AKC695X devices
Parameters
reg register number to be written (only for RW type registers)
parameter value to be written in the register
References AKC695X::deviceAddress.
Referenced by AKC695X::commitTune(), AKC695X::powerOn(), AKC695X::seekStation(), AKC695X::setAM(), AKC695X::setAudio(), AKC695X::setCustomBand(), AKC695X::setFM(), AKC695X::setFmSeekStep(), AKC695X::setFrequency(), AKC695X::setVolume(), and AKC695X::setVolumeControl().
setup()
void AKC695X::setup (int resetPin)
Receiver startup.
Parameters
resetPin if >= 0, then you control the RESET. if -1, you are using ths MCU RST pin.
References AKC695X::reset(), and AKC695X::resetPin.